### ISSUE TITLE
上传超过 4GB 的视频失败

### ISSUE THREAD

**Issue by vicat47** [ForgQi/biliup-rs#14]
在通过命令行上传时，视频体积超过 4GB 的话会报错，`attempt to add with overflow`。包括 `qn` 和 `ws` 都会发生该错误。
```
thread 'main' panicked at 'attempt to add with overflow', biliup-rs/src/uploader/upos.rs:121:26
```

**Comment by ForgQi** [comment]
你是本地32位机器，调试时出的这个问题吗

**Comment by ForgQi** [comment]
> > 你是本地32位机器，调试时出的这个问题吗
> 
> 设备是 armv7l 的树莓派 4B，内存 4GB，那估计就是这个问题了。 我今晚又在 win11 64位的机器上试了试，是可以上传超过 4GB 的内容的。

这个问题想修复的话，把`biliup-rs/src/uploader/upos.rs:121:26`从usize改成u64就可以了

**Comment by vicat47** [comment]
用 64 位操作系统运行了
