### ISSUE TITLE
支持多账号

### ISSUE THREAD

**Issue by ttys000** [ForgQi/biliup-rs#21]
希望可以为项目贡献多账号管理的功能，例如：

- 管理多个账号，包括登入登出、上传
- 不知道能否实现以某个账号的 cookie 打开 bilibili.com

**Comment by ttys000** [comment]
> 

好的，第二个问题有什么思路么？

**Comment by ttys000** [comment]
> 可以，如果想PR建议增加传入cookie文件路径的功能，应该就能做到多账户

好的，第二个问题有什么思路么？

**Comment by ForgQi** [comment]
浏览器自动化看chromedriver之类的，这边需要可以在无浏览器环境下运行，不会提供相关功能

**Comment by ttys000** [comment]
已实现
