### ISSUE TITLE
doc需求

### ISSUE THREAD

**Issue by kumaneru** [ForgQi/biliup-rs#3]
主要是想知道如何加参数选择转载/分区/封面等内容。

**Comment by ForgQi** [comment]
补充了一些关于配置文件的文档

**Comment by kumaneru** [comment]
翻出别人的文档填了半天，然后遇到Error: Pattern syntax error near position 12: recursive wildcards must form a single path component真的不知道该怎么改了…

**Comment by ForgQi** [comment]
别人的文档是哪里翻得，可以把配置贴出来看一下

**Comment by kumaneru** [comment]
https://bili.moyu.moe/#/modules/video_uploader

user:
  account:
    username: your username
    password: your password
streamers:
  视频patterns1*:
    copyright: 2
    source: test
    tid: 152 
    cover: "./11.png"
    title: test
    desc_format_id: 0
    desc: biliup_test
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: "test"
    videos: [{title: 'test',
              desc: 'part_desc',
              filename: '000.mp4'}]
    dtime: ~
    open_subtitle: false

**Comment by ForgQi** [comment]
下新版本试下吧，不要填videos，填了也不会起作用的

**Comment by kumaneru** [comment]
line: kodo

streamers:
  视频patterns1*:
    copyright: 2
    source: test
    tid: 152 # 投稿分区
    cover: "" # 视频封面
    title: test
    desc_format_id: 0
    desc: test
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: "test"
    dtime: ~
    open_subtitle: false

>biliup upload -c config.yaml 000.mp4
通过cookie登录
未搜索到匹配的视频文件：视频patterns1*

**Comment by ForgQi** [comment]
https://github.com/ForgQi/biliup-rs#useage
看配置文件的文档

**Comment by kumaneru** [comment]
{视频patterns1*}只能使用匹配规则，如果想使用类似于“fnjE6XKCaeJ_3EXI.mp4 000.mp4（防撞车p2）”这样的文件投分p是只能把这两个视频一起移入一个文件夹之后匹配而不能直接写两个文件名吗…

**Comment by ForgQi** [comment]
那你可以把匹配写成*.mp4

**Comment by kumaneru** [comment]
虽然我本意是我一般使用的文件夹里有大量视频，我换个例子吧…
p1 みんなかもん！田中美海の生誕祭2022(にーまるにーにー).ts  p2 000.mp4 这样

**Comment by ForgQi** [comment]
如果只是要单次投稿多p直接`biliup upload xxx.mp4 xxx.mp4`就可以了，配置文件是为了大量多次投稿用的，所以用匹配的方式更灵活不用每次都改配置，你这个情况直接匹配文件夹吧`videos/*`

**Comment by ForgQi** [comment]
如果用列出文件的方式会写的很长，每次投稿都要大量修改，那只有用另一个[GUI工具](https://github.com/ForgQi/Caution)能批量选择才能比较方便吧，我个人是认为列出十几个文件，每次都要改的话是很痛苦的事情

**Comment by kumaneru** [comment]
我只是想固定p2防撞杆而已，一般标题和p1相同，所以还是感觉使用命令行更方便我传入信息（至少我的wt是一直开着，biliup-app不是

**Comment by ForgQi** [comment]
那是不想使用文件夹匹配`videos/*`吗

**Comment by ForgQi** [comment]
如果没有其他的，这个issue先close了，有觉得更合适的方案同时兼容大量视频可以提出来, 再open吧
