### ISSUE TITLE
国内上传速度只能到3m左右 网络测试是能到25m上传速度的 每个上传路线都一样 并发是在3个 

### ISSUE THREAD

**Issue by Morii120** [ForgQi/biliup-rs#30]
但是一个配置文件只放一个视频组上传
![image](https://user-images.githubusercontent.com/13359932/173097428-9f2d3c1d-afe4-411f-a196-d3b47e6f0905.png)
然后会有同时三个这样配置文件 通过window安装包上传
上传的成功返回日志 只有1m/s左右上传速度
![image](https://user-images.githubusercontent.com/13359932/173097631-445d72db-d098-47f5-a6c4-eafdc7b9b13d.png)
有没有办法把上传带宽都利用起来呢

**Comment by Morii120** [comment]
谢谢 大佬回复 我试过国内的路线了 也是一样的 配置文件合并后好像也没有效果 也是一个一个上传

**Comment by ForgQi** [comment]
肯定是一个个上传，没到带宽就调大并发数
