### ISSUE TITLE
[需求] 关于其他版本的Release

### ISSUE THREAD

**Issue by Small-Miao** [ForgQi/biliup-rs#31]
希望大佬们能编译一个NPM包版本使用
有点研究不明白 rust 的 [napi-rs](https://github.com/napi-rs/napi-rs)
求编译个NPM版本 并release

**Comment by ForgQi** [comment]
有点没太明白具体是需要什么，加QQ群：837362626说一下吧

**Comment by limitcool** [comment]
> 是否可以扩展出一个HTTP API 来与这个客户端进行交互呢

大佬可以试下这个[biliup-http](https://github.com/limitcool/biliup-http)。
