### ISSUE TITLE
上传时莫名报错Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Quandong-Zhang** [ForgQi/biliup-rs#40]
![image](https://user-images.githubusercontent.com/78526012/180213336-2253c856-f2f7-4771-9b98-c5ecc3f289f7.png)
如图，线路用的是cos,服务器在美国洛杉矶，OS版本是Ubuntu18。

**Comment by ForgQi** [comment]
把自己代码贴出来，版本贴出来，如果设置了封面，确认路径都在

**Comment by Quandong-Zhang** [comment]
[这里](https://github.com/Quandong-Zhang/youtube-trans-bot)是我自己的代码 
版本[v0.1.11](https://github.com/ForgQi/biliup-rs/releases/tag/v0.1.11)
没有设定封面，不是每个视频都有此问题，只有这个视频会出错
`
https://www.youtube.com/watch?v=uLWXXAVNAGs
`
同时调用的方式为命令行管道（python中的os.system）
命令行调用格式类似于
```shell
./biliup upload ./gqmsj7W2VGc/*.* --desc "みなさんこんにちは！！
【藤家溪子の合唱曲】
楽しんでいただいてますか？？

今回は先日公開した『いっすんぼうしの雨』の特別バージョン！


今日7月20日は
映画「森の学校」が公開20周年(2002年7月20日公開）を迎えます！
音楽担当は尾高賞を2度も受賞された藤家溪子さん

劇中ではテーマソングが子どもたちのうたごえや楽器演奏で何度も流れてきます！

今回は
実際に映画で歌われた歌詞の
合唱バージョンでお届け！！







『東混サブスク』
・過去の定期演奏会
・制作の舞台裏
・ここで" --copyright 2 --tag "'東京混声合唱団', '合唱', 'クラシック音楽', '声楽', '山田和樹', 'コーラス', 'Chorus', '日本', 'Japan', 'Tokyo,youtube" --tid 21 --source "https://www.youtube.com/watch?v=gqmsj7W2VGc" --line cos --dynamic "@Rerange" --title "いっすんぼうしの雨三浦春馬主演映画森の学校テーマソング合唱バージョン"
```

**Comment by Quandong-Zhang** [comment]
开始怀疑是命令行调用带回车导致的，但因为它提示的是找不到文件，跟参数没关系，同时把描述去掉改为`-`也没用，还有除了它其他的视频都好使，所以我觉得原因应该不是

**Comment by ForgQi** [comment]
命令行上传不支持通配符

**Comment by Quandong-Zhang** [comment]
> 命令行上传不支持通配符

好的（顺便问下为啥没在文档里说明【doge】）

**Comment by ForgQi** [comment]
文档里只说了配置文件支持通配符

**Comment by Quandong-Zhang** [comment]
> 文档里只说了配置文件支持通配符

好吧，但希望能加一下命令行不支持通配符的提醒，毕竟从程序设计的角度看从配置文件和命令行获得参数会下意识的认为并无不同。
