### ISSUE TITLE
交叉编译arm-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by lovegaoshi** [ForgQi/biliup-rs#42]
请求发布交叉编译arm-unknown-linux-gnueabi的版本，可以在asusmerlin上用

**Comment by ForgQi** [comment]
有ARM的包

**Comment by lovegaoshi** [comment]
> 有ARM的包

armv7的在asusmerilin上用不了，只有这个arm-unknown-linux-gnueabi的toolchain能用

**Comment by ForgQi** [comment]
加了[arm-linux](https://github.com/ForgQi/biliup-rs/releases/download/v0.1.13/biliupR-v0.1.13-arm-linux.tar.xz)
