### ISSUE TITLE
Compile Error on rust 1.61.0

### ISSUE THREAD

**Issue by YangchenYe323** [ForgQi/biliup-rs#56]
Hi I'm new to biliup-rs! I'm trying to compile the project using rust 1.61.0, but got the following compiler error:
<img width="1144" alt="Screen Shot 2022-12-16 at 6 33 24 AM" src="https://user-images.githubusercontent.com/42916814/208099181-9a9ab463-8f52-4483-ae35-46641f02a59f.png">
Seems I'm missing a database file? What should I add to make it work? Thanks for any advice!

**Comment by ForgQi** [comment]
在项目的根目录创建一个叫data.db的空文件就可以了

**Comment by YangchenYe323** [comment]
> 在项目的根目录创建一个叫data.db的空文件就可以了

感谢回复！我创建了空的data.db文件，但是又碰到了下图的报错：
<img width="1420" alt="Screen Shot 2022-12-18 at 2 55 10 PM" src="https://user-images.githubusercontent.com/42916814/208318916-f191faaf-6c6f-471b-81f3-2abf161b2ec3.png">
请问这个要怎么解决？

**Comment by ForgQi** [comment]
cargo sqlx migrate run --source .\crates\biliup\migrations\

**Comment by YangchenYe323** [comment]
> cargo sqlx migrate run --source .\crates\biliup\migrations\

这个解决了上面的问题，之后在编译的时候遇到一个linker的报错（在MacOS上编译）。添加以下的`.cargo/config`文件之后就能成功运行了（https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1）：
```
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

**Comment by ttys000** [comment]
建议不要提交不能通过 cargo build 的 PR，main branch 任何时候都应该可以成功的 cargo build。
