### ISSUE TITLE
请问怎么通过配置文件进行多P投稿？

### ISSUE THREAD

**Issue by Postroggy** [ForgQi/biliup-rs#6]
在示例的`config.yaml`文件中没发现多P投稿、是否选择为合集的选项。求指教

**Comment by Postroggy** [comment]
好像是需要在一个streamers元素里面匹配全部的视频就能分P？多个ｓｔｒｅａｍｅｒ元素对应多个视频会投稿成独立的。
多P投稿的视频标题是需要投稿完了之后再在web端一个个修改吗？希望README能够更加详细的说明下。这个项目挺不错的。

**Comment by ForgQi** [comment]
指的是每个分p的标题吗，还是指的是视频总标题

**Comment by Postroggy** [comment]
@ForgQi 指的是分P的标题，另外我发现用通配符匹配多个视频，因为我投稿的是转载类型，只有第一个视频的有转载来源，其他的视频没有转载来源。
![image](https://user-images.githubusercontent.com/53985742/152631032-33380adf-53ae-41d9-9ae2-3291083c65ea.png)
我的配置文件：
![image](https://user-images.githubusercontent.com/53985742/152631118-99e95058-1aa5-4b41-bd48-5292d5959356.png)

**Comment by ForgQi** [comment]
设置转载填2，不是0，分p标题是文件名

**Comment by Postroggy** [comment]
@ForgQi 可以了，看了文档还没看懂，感觉可以 更新下文档，更详细一点

**Comment by Postroggy** [comment]
@ForgQi 请问多个 tag 是用 `,` 英文的逗号隔开吗？
![image](https://user-images.githubusercontent.com/53985742/152633374-074afcf9-02a5-4b79-922a-afa5f1629cad.png)
