### ISSUE TITLE
如何对已上传的视频追加分P

### ISSUE THREAD

**Issue by vicat47** [ForgQi/biliup-rs#8]
如题，是否可以配置呢？
我自己扒拉了一下上传过程，没看到上传和稿件做绑定的地方
可不可以指定链接进行稿件追加呢？

**Comment by ForgQi** [comment]
理论上可以，目前只能上传不能追加

**Comment by flrscn** [comment]
同求这个功能。
我这里需要录制的直播间每场直播很长，最长有20小时，而且码率高达13M。如果全部录完后再上传，不但会占用大量磁盘空间，而且上传时间也非常长。所以需要边录制边投稿：每录一段时间就分段并立即追加至已有稿件。
其它部分都已完成，只差追加分P的功能。

**Comment by zsb514** [comment]
今天又仔细看了下，添加调的是 add 接口，如果想要追加分 P的话需要调
`https://member.bilibili.com/x/vu/web/edit?csrf=df67xxxxxxxxxxxxxxxxxxxxxxxac4b` 这个接口。
```json
{
  "copyright": 1,
  "videos": [
    {
      "filename": "n2202270xxxxxxxxxxxxxxxxxxx856u2tjl",
      "title": "1P",
      "desc": "",
      "cid": 517941634,
      "editor": {
        "fonts": "",
        "stickers": "",
        "web_cover_template": ""
      }
    },
    {
      "filename": "n2202270xxxxxxxxxxxxxxxx2a9j063sce",
      "title": "2P",
      "desc": "",
      "cid": 517935923,
      "editor": {
        "fonts": "",
        "stickers": "",
        "web_cover_template": ""
      }
    },
//   。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
//   。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
    {
      "filename": "n22032xxxxxxxxxxxxxxxxx8i1dhloxdt9",
      "title": "Binding of Isaac_ Repentance 2021-09-11 00-42-19",
      "desc": "",
      "cid": 557333707,
      "editor": {
        "fonts": "",
        "stickers": "",
        "web_cover_template": ""
      }
    }
  ],
  "no_reprint": 1,
  "interactive": 0,
  "tid": 17,
  "cover": "//i2.hdslb.com/bfs/archive/d527xxxxxxxxxxxxxxxxxxxxxxxxxxxxx618a17.jpg",
  "title": "这里是标题",
  "tag": "单机,新人,游戏视频",
  "desc_format_id": 28,
  "desc": "受苦开始",
  "dynamic": "",
  "open_elec": 1,
  "subtitle": {
    "open": 0,
    "lan": ""
  },
  "handle_staff": false,
  "is_360": -1,
  "act_reserve_create": 0,
  "origin_state": 0,
  "aid": 这个是AV号，是个number,
  "topic_grey": 1
}
```
似乎是只要有av号就可以追加分 P

**Comment by zsb514** [comment]
请问最近又支持这个功能的打算么？我不会写 `Rust` 代码。逻辑倒是挺清晰也很简单，如果没有这方面的计划的话我自己看看能不能改。。

**Comment by ForgQi** [comment]
> 请问最近又支持这个功能的打算么？我不会写 `Rust` 代码。逻辑倒是挺清晰也很简单，如果没有这方面的计划的话我自己看看能不能改。。
> 
> @ForgQi 感谢

这块的交互怎么做还不太清楚。如果大佬有改的打算，能提个PR更好，先感谢大佬了

**Comment by zsb514** [comment]
#12 功能基本可用。

**Comment by Begnion** [comment]
{"code":21138,"message":"超出当前可用分p视频数上限","ttl":1}
Error: {"code":21138,"message":"超出当前可用分p视频数上限","ttl":1}
append的时候报这个错怎么破，B站6级号。

**Comment by vicat47** [comment]
你是在对当前只有一个分p的视频进行追加么？
在编写代码的时候我是使用的 web 接口进行抓包和测试的，b站web端对视频追加有限制，只有你在创建稿件的时候是分p的，那么才能在web端增加分p。客户端上传没有这个限制
以后可能会修改为客户端的修改稿件接口。
现在的办法是，先使用客户端创建多p视频再进行追加。

**Comment by vicat47** [comment]
> {"code":21138,"message":"超出当前可用分p视频数上限","ttl":1} Error: {"code":21138,"message":"超出当前可用分p视频数上限","ttl":1} append的时候报这个错怎么破，B站6级号。

你是在对当前只有一个分p的视频进行追加么？
在编写代码的时候我是使用的 web 接口进行抓包和测试的，b站web端对视频追加有限制，只有你在创建稿件的时候是分p的，那么才能在web端增加分p。客户端上传没有这个限制
以后可能会修改为客户端的修改稿件接口。
现在的办法是，先使用客户端创建多p视频再进行追加。

**Comment by vicat47** [comment]
我看了下接口，明天改吧，要动的东西不多
@Begnion

**Comment by vicat47** [comment]
#15 
已修复。
@Begnion
