### ISSUE TITLE
简介中换行如何表达

### ISSUE THREAD

**Issue by BeanKaKa** [ForgQi/biliup-rs#9]
尝试使用了\n无法换行，求大佬解答

**Comment by ForgQi** [comment]
yaml语法：https://www.ruanyifeng.com/blog/2016/07/yaml.html

**Comment by zhuhongjie** [comment]
> yaml语法：https://www.ruanyifeng.com/blog/2016/07/yaml.html

如果是命令行直接上传，不用yml模板可以实现换行吗？
